// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"authentication.mdx": () => import("../content/docs/authentication.mdx?collection=docs"), "introduction.mdx": () => import("../content/docs/introduction.mdx?collection=docs"), "quickstart.mdx": () => import("../content/docs/quickstart.mdx?collection=docs"), "api-reference/create-refund.mdx": () => import("../content/docs/api-reference/create-refund.mdx?collection=docs"), "api-reference/get-refund.mdx": () => import("../content/docs/api-reference/get-refund.mdx?collection=docs"), "api-reference/get-transaction.mdx": () => import("../content/docs/api-reference/get-transaction.mdx?collection=docs"), "api-reference/introduction.mdx": () => import("../content/docs/api-reference/introduction.mdx?collection=docs"), "api-reference/list-refunds.mdx": () => import("../content/docs/api-reference/list-refunds.mdx?collection=docs"), "api-reference/list-transactions.mdx": () => import("../content/docs/api-reference/list-transactions.mdx?collection=docs"), "api-reference/query-audit.mdx": () => import("../content/docs/api-reference/query-audit.mdx?collection=docs"), "guides/calculation-engine.mdx": () => import("../content/docs/guides/calculation-engine.mdx?collection=docs"), "guides/financial-precision.mdx": () => import("../content/docs/guides/financial-precision.mdx?collection=docs"), "guides/how-refunds-work.mdx": () => import("../content/docs/guides/how-refunds-work.mdx?collection=docs"), "guides/validation-pipeline.mdx": () => import("../content/docs/guides/validation-pipeline.mdx?collection=docs"), "reference/business-rules.mdx": () => import("../content/docs/reference/business-rules.mdx?collection=docs"), "reference/error-codes.mdx": () => import("../content/docs/reference/error-codes.mdx?collection=docs"), "scenarios/scenario-a.mdx": () => import("../content/docs/scenarios/scenario-a.mdx?collection=docs"), "scenarios/scenario-b.mdx": () => import("../content/docs/scenarios/scenario-b.mdx?collection=docs"), "scenarios/scenario-c.mdx": () => import("../content/docs/scenarios/scenario-c.mdx?collection=docs"), "scenarios/scenario-d.mdx": () => import("../content/docs/scenarios/scenario-d.mdx?collection=docs"), "scenarios/scenario-e.mdx": () => import("../content/docs/scenarios/scenario-e.mdx?collection=docs"), }),
};
export default browserCollections;